<?php

/*
 * TODO: Be able to graph userdata when that's available.
 * At the moment this only graphs altitude data, of course this
 * needs to change. Multiple lines with multiple axis would also
 * be nice.
 */

DEFINE('DEFAULT_GRAPH_FORMATTER', 'default');

DEFINE('TRACKFIELD_GRAPH_PATH', 'trackfield_graph/graph');
DEFINE('TRACKFIELD_GRAPHDATA_JQPLOT_PATH', 'trackfield_graph/jqplotdata');
DEFINE('TRACKFIELD_GRAPHDATA_PATH', 'trackfield_graph/graphdata');

/*
 * Implementation of hook_menu().
 */

function trackfield_graph_menu() {
  $items = array();

  $items[TRACKFIELD_GRAPH_PATH] = array(
    'type' => MENU_CALLBACK,
    'access callback' => 'user_access', 
    'access arguments' => array('access content'),
    'page callback' => '_trackfield_graph_do_graph',
  );
  $items[TRACKFIELD_GRAPHDATA_JQPLOT_PATH] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => '_trackfield_graph_do_graphdata_jqplot',
  );
  $items[TRACKFIELD_GRAPHDATA_PATH] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => '_trackfield_graph_do_graphdata',
  );

  /* Admin menu */
  $access = user_access('administer trackfield');
  $items['admin/settings/trackfield/graph'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => t('Graphs'),
    'description' => t('Settings for trackfield graphs.'),
    'access arguments' => array('administer trackfield'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_trackfield_graph_admin'));

  return $items;
}

/***************************************************************
 * Field Type API hooks
 ***************************************************************/

/**
 * Implements hook_field_info().
 *
 * Provides the description of the field.
 */
function trackfield_graph_field_info() {
  return array(
    'trackgraph' => array(
      'label' => t('Track Graph'),
      'description' => t('Graphs data held in a Track field.'),
      'default_widget' => 'trackfield_graph_none',
      'default_formatter' => 'trackfield_graph_default',
    ),
  );
}

/**
 * Implements hook_field_delete().
 */
function trackfield_graph_field_delete($entity_type, $entity, $field, $instance, $langcode, &$items) {
	  }

/**
 * Implements hook_field_validate().
 */
function trackfield_graph_field_validate ($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {

	 }

/**
 * Implements hook_field_presave().
 */
function trackfield_graph_field_presave ($entity_type, $entity, $field, $instance, $langcode, &$items, &$errors) {

      }

/**
 * Implements hook_field_update().
 */
function trackfield_graph_field_update($entity_type, $entity, $field, $instance, $langcode, &$items) {
    }

/**
 * Implements hook_field_insert().
 */
function trackfield_graph_field_insert($entity_type, $entity, $field, $instance, $langcode, &$items) {
    
     }


/**
 * Implements hook_field_is_empty().
 */
function trackfield_graph_field_is_empty($item, $field) {
  return FALSE;
}

/**
 * Implementation of hook_field_settings_form().
 */
function trackfield_graph_field_settings_form($field, $instance, $has_data) {
  
	 	$settings = $field['settings'];
	
      global $_trackfield_norm_types;
      $form = array(
        'reference_field_name' => array(
          '#type' => 'textfield',
          '#rows' => 1,
          '#title' => t('Reference Field Name'),
          '#default_value' => isset($settings['reference_field_name']) ? $settings['reference_field_name'] : '',
          '#required' => true
        ),
        'normalise' => array(
          '#type' => 'select',
          '#title' => t('Normalise As'),
          '#default_value' => isset($settings['normalise']) ? $settings['normalise'] : '',
          '#options' => $_trackfield_norm_types,
        )
      );
      
      $form['#element_validate'] = array('trackfield_graph_settings_form_validate');
      
      return $form;
  }
  
function trackfield_graph_settings_form_validate($element, &$form_state) {
	
	$valid_fields = array();
	 if (!in_array($element['reference_field_name']['#value'], $valid_fields = _trackfield_fields())) {
        if (array_count_values($valid_fields) == 0) {
          form_set_error('reference_field_name', t('You must specify the reference field of type track, but appear not to have any defined!'));
        } else {
          form_set_error('reference_field_name', t('You must specify the reference field of type track. Valid fields in this system: %fields', array('%fields' => join(', ', $valid_fields))));
        }
  		}
    }



/***********************************************************************
 *  Field Type API: Formatter
 *
 *  These are the api hooks that present formatted (themed) output to the
 *  user.
 **********************************************************************/

/**
 * Implements hook_field_formatter_info().
 */
function trackfield_graph_field_formatter_info() {

  $formatters = array();
  $trackfield_format_sizes = variable_get('trackfield_graph_format_sizes', array());
  foreach (array_keys($trackfield_format_sizes) as $formatter) {
    $formatters['trackfield_graph_' . ($formatter)] = array('label' => t($formatter), 'field types' => array('trackgraph'));
  }

  return $formatters; 

}

/**
 * Implements hook_field_formatter_view().
 */
function trackfield_graph_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();  
  $settings = $field['settings'];
  krumo($display['type']);
  
  foreach($items as $delta => $item) {
  $value = isset($item['value']) ? check_plain($item['value']) : NULL;
  
  switch($display['type']) {
  
  case 'trackfield_graph_default':
  default :
  	  
  $ref_field_name = $settings['reference_field_name'];
  $normalise = $settings['normalise'];

  /*
   * We can't draw anything if there's no altitude data.
   */
  $fset = $entity->{$ref_field_name}[$langcode];
  if (!in_array('altitude', explode(',', $fset[$delta]['trackdatasets']))) { return 'No Altitude'; }

  /*
   * We can't draw anything for previews.
   */
  //if ($entity->in_preview == TRUE) { return 'Graph is not available in preview'; }

  /*
   * Look in the sizes array for definitions matchin the formatter
   * and create image link for that.
   */

  $formatter = (substr($display['type'], strlen('trackfield_graph_')));
  $out = _trackfield_graph_render($formatter, $entity->nid . ',' . $entity->vid . ',' . $ref_field_name, $normalise);
krumo($out);
  $element[$delta]['#markup'] = 	$out;
    
  return $element;
  }
  }
  }


/**************************************************************************
 * Field Type API: Widget
 *
 * The widget is the form element used to receive input from the user
 * when the field is being populated.
 **************************************************************************/

/**
 * Implements hook_field_widget_info().
 */
function trackfield_graph_field_widget_info() {
  return array(
    'trackfield_graph_none' => array(
      'label' => t('None Required'),
      'field types' => array('trackgraph'),
    ),	
  );
}

/**
 * Implements hook_field_widget_settings_form().
 */
function trackfield_graph_field_widget_settings_form($field, $instance) {
}

/**
 * Implements hook_field_widget_form().
 */
 
function trackfield_graph_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
 
   switch ($instance['widget']['type']) {
	
    case 'trackfield_graph_none':
    
    /* Is this necessary? */
	 /*
     * If we don't return at least a blank array then this field
     * will not appear in the 'manage fields' tab inside content.
     */
    
        $element['value'] = array(
        '#type' => 'hidden',	
        '#title' => 'Graph Placeholder...',
        '#required' => FALSE,
        '#default_value' => NULL,	
      );
  break; 
  }

  return $element;

}

function _trackfield_graph_render($formatter, $args, $normalise) {
  static $jqplot_ids = 1;

  $trackfield_format_sizes = variable_get('trackfield_graph_format_sizes', array());
  
  if ($trackfield_format_sizes[$formatter]['renderer'] == 'jqplot') {
    /* Render with jqplot */
    krumo('BOO!');
    $id = 'trackfield_jqplot_' . $jqplot_ids++;

    drupal_add_js(drupal_get_path('module', 'trackfield') . '/jqplot/jquery.jqplot.min.js');
    drupal_add_js(drupal_get_path('module', 'trackfield') . '/jqplot/plugins/jqplot.categoryAxisRenderer.js');
    drupal_add_js(drupal_get_path('module', 'trackfield') . '/jqplot/plugins/jqplot.cursor.js');
    drupal_add_js(drupal_get_path('module', 'trackfield') . '/jqplot/plugins/jqplot.highlighter.js');
    drupal_add_css(drupal_get_path('module', 'trackfield') . '/trackfield_jqplot.css');
    drupal_add_js(drupal_get_path('module', 'trackfield') . '/trackfield_jqplot.js');
    $settings = array(
      'JqplotDataUrl' => url('trackfield_graph/jqplotdata'),
    );
    drupal_add_js(array('trackfield_graph' => $settings), 'setting');
    
    $out = sprintf('<div id="%s" class="plot trackfield" style="width:%dpx;height:%dpx"><div class="args">%s</div></div>',
      $id,
      $trackfield_format_sizes[$formatter]['width'],
      $trackfield_format_sizes[$formatter]['height'],
      $args . '/' . $formatter . '/' . $normalise);
  } else {
    /* Render with JpGraph */
    $out = sprintf('<img width="%d" height="%d" src="%s"/>',
      $trackfield_format_sizes[$formatter]['width'],
      $trackfield_format_sizes[$formatter]['height'],
      urldecode(url(TRACKFIELD_GRAPH_PATH . '/' . $args . '/' . $formatter . '/' . $normalise)));
  }
  
  return $out;
}

function _trackfield_graph_do_graph() {
  include_once(drupal_get_path('module', 'trackfield_graph') .'/trackfield_graph.inc');
  
  
  $args = _trackfield_graph_graphargs();
  _trackfield_graph(_trackfield_graph_graphargs());
}

function _trackfield_graph_graphargs() {
  /*
   * Get arguments for passing to graph and graphdata functions.
   * These are encoded as arg(2)...
   * The URL is something like:
   * TRACKFIELD_GRAPH_PATH/graph/nid,vid,field[[,delta],[xset,yset]];...nid,vid,field[,delta]/size(/normalise)
   * or
   * TRACKFIELD_GRAPH_PATH/graphdata/nid,vid,field[,delta]
   * 
   * If more than one item is given, but nid,vid,field is ommitted the previous is assumed.
   * If delta is ommitted zero is assumed.
   * Eg.
   * TRACKFIELD_GRAPH_PATH/graph/nid,vid,field;,,,,distance,heartrate
   * Will graph distance/altitude (default) plus distance/heartrate
   */
    
  $itemlist = array();
  $xset = 'distance';
  $yset = 'altitude';
  $delta = 0;
  
  foreach(explode(';', arg(2)) as $item) {
    $parts = explode(',', $item);
    if (isset($parts[0]) && $parts[0] != '') { $nid = $parts[0]; }
    if (isset($parts[1]) && $parts[1] != '') { $vid = $parts[1]; }
    if (isset($parts[2]) && $parts[2] != '') { $field = $parts[2]; }
    if (isset($parts[3]) && $parts[3] != '') { $delta = $parts[3]; }
    if (isset($parts[4]) && $parts[4] != '') { $xset = $parts[4]; }
    if (isset($parts[5]) && $parts[5] != '') { $yset = $parts[5]; }
    $itemlist[] = array(
      'nid' => $nid,
      'vid' => $vid,
      'field' => $field,
      'delta' => $delta,
      'xset' => $xset,
      'yset' => $yset,
    );
  }
  
  $args = array(
    'items' => $itemlist
  );
  $args['formatter'] = arg(3) ? arg(3) : DEFAULT_GRAPH_FORMATTER;
  $args['normal_type'] = arg(4) ? arg(4) : TRACKFIELD_DEFAULT_NORM;
  
  return $args;
}


/*
 * Admin page below here.
 */

include_once(drupal_get_path('module', 'trackfield') .'/jpgraph/src/jpgraph_ttf.inc.php');

function _trackfield_is_fixed_jpgraph_font($font) {
  if ($font == FF_FONT0 ||
      $font == FF_FONT1 ||
      $font == FF_FONT2) return TRUE;
  return FALSE;
}

function _trackfield_graph_admin() {
  $trackfield_format_sizes = variable_get('trackfield_graph_format_sizes', array());
  /* Add a blank line for new entries */
  $trackfield_format_sizes[''] = array();
  
  $form['sizes'] = array(
    '#type' => 'fieldset',
    '#title' => t('Graph sizes'),
    '#tree' => TRUE,
    '#theme' => 'trackfield_graph_sizes_form',
    '#description' => t('Various size graphing options are available whenever these are shown (in teaser, full node, views, etc). Define the possible choices required here.<br>Margins are "left,right,top,bottom"')
  );

  $jpgraph_fonts = array(
    FF_FONT0 =>     'FF_FONT0',
    FF_FONT1 =>     'FF_FONT1',
    FF_FONT2 =>     'FF_FONT2',
    FF_VERA =>      'FF_VERA',
    FF_VERAMONO =>  'FF_VERAMONO',
    FF_VERASERIF => 'FF_VERASERIF',
  );

  $lp = 0;
  foreach ($trackfield_format_sizes as $key => $config) {

    if(isset($config['margins'])) {
    	$margins = is_array($config['margins']) ? join(',', $config['margins']) : $config['margins'];
    	}
    else {
    	$margins = '';
    	}  	


    $form['sizes'][$lp]['del'] = array(
      '#type' => 'checkbox',
    );
    $form['sizes'][$lp]['label'] = array(
      '#type' => 'textfield',
      '#default_value' => $key,
      '#size' => 15,
      '#maxlength' => 32,
    );
    $form['sizes'][$lp]['renderer'] = array(
      '#type' => 'select',
      '#default_value' => $config ? $config['renderer'] : 'jqplot',
      '#options' => array('jpgraph' => 'jpgraph', 'jqplot' => 'jqplot'),
    );
    $form['sizes'][$lp]['width'] = array(
      '#type' => 'textfield',
      '#default_value' => $config ? $config['width'] : '',
      '#size' => 4,
      '#maxlength' => 5,
    );
    $form['sizes'][$lp]['height'] = array(
      '#type' => 'textfield',
      '#default_value' => $config ? $config['height'] : '',
      '#size' => 4,
      '#maxlength' => 5,
    );
    $form['sizes'][$lp]['weight'] = array(
      '#type' => 'textfield',
      '#default_value' => $config ? $config['weight'] : '',
      '#size' => 2,
      '#maxlength' => 3,
    );
    $form['sizes'][$lp]['margins'] = array(
      '#type' => 'textfield',
      '#default_value' => $margins,
      '#size' => 8,
      '#maxlength' => 25,
    );
    $form['sizes'][$lp]['axis'] = array(
      '#type' => 'checkbox',
      '#default_value' => $config ? $config['axis'] : false,
    );
    $form['sizes'][$lp]['axis_font'] = array(
      '#type' => 'select',
      '#default_value' => $config ? $config['axis_font'] : 2,
      '#options' => $jpgraph_fonts,    
    );
    $form['sizes'][$lp]['axis_font_size'] = array(
      '#type' => 'textfield',
      '#default_value' => $config ? $config['axis_font_size'] : '',
      '#size' => 2,
      '#maxlength' => 5,
    );
    $form['sizes'][$lp]['legend'] = array(
      '#type' => 'checkbox',
      '#default_value' => $config ? $config['legend'] : false,
    );
    $form['sizes'][$lp]['resample'] = array(
      '#type' => 'textfield',
      '#default_value' => $config ? $config['resample'] : '',
      '#size' => 2,
      '#maxlength' => 5,
    );
    $lp++;
  }
  
  $trackfield_format_cols = variable_get('trackfield_graph_format_cols', array());
  /* Add a blank line for new entries */
  $trackfield_format_cols[''] = array();
  
  $form['cols'] = array(
    '#type' => 'fieldset',
    '#title' => t('Graph colours'),
    '#tree' => TRUE,
    '#theme' => 'trackfield_graph_cols_form',
    '#description' => t('What colour should various datasets be shown as.<br/>Special codes are "background" and "axis" (fill is ignored for both).<br/>Jpgraph supports alpha blending which is useful when multiple sets are charted together by adding "@<em>alpha</em>" (eg. "@0.5").<br/>Comma separated lists rotate if multiple data sets are charted.')
  );

  $lp = 0;
  foreach ($trackfield_format_cols as $key => $config) {
  	
    if(isset($config['fill_col'])) {
    	$fill_col = is_array($config['fill_col']) ? join(',', $config['fill_col']) : $config['fill_col'];
    	}
    else {
    	$fill_col = '';
    	}
    	
    if(isset($config['col'])) {
    	$col = is_array($config['col']) ? join(',', $config['col']) : $config['col'];
    	}
    else {
    	$col = '';
    	}  	
  	
    $form['cols'][$lp]['del'] = array(
      '#type' => 'checkbox',
    );
    $form['cols'][$lp]['label'] = array(
      '#type' => 'textfield',
      '#default_value' => $key,
      '#size' => 15,
      '#maxlength' => 32,
    ); 
    $form['cols'][$lp]['col'] = array(
      '#type' => 'textfield',
      '#default_value' => $col,
      '#size' => 20,
      '#maxlength' => 128,
    );   
    $form['cols'][$lp]['fill_col'] = array(
      '#type' => 'textfield',
      '#default_value' =>  $fill_col,
      '#size' => 20,
      '#maxlength' => 128,
    );
    $lp++;
  }

  $form['misc'] = array(
    '#type' => 'fieldset',
    '#title' => t('Miscellaneous'),
    '#tree' => TRUE,
  );

  $form['misc']['multiple_fill_threshold'] = array(
    '#type' => 'textfield',
    '#title' => t('Multiple Fill Threshold'),
    '#suffix' => t('When multiple datasets are charted together, how many should be filled?'),
    '#default_value' => variable_get('trackfield_graph_multiple_fill_threshold', 0),
    '#size' => 3,
    '#maxlength' => 3,
  );

  $form['misc']['ttf_path'] = array(
    '#type' => 'textfield',
    '#title' => t('TTF Path'),
    '#suffix' => t('Relative to JpGraph root (not src) directory. Requires trailing slash'),
    '#default_value' => variable_get('trackfield_graph_ttf_path', ''),
    '#size' => 40,
    '#maxlength' => 128,
  );

  $form['buttons']['submit'] = array('#type' => 'submit', '#value' => t('Save configuration') );
  $form['buttons']['delete'] = array('#type' => 'submit', '#value' => t('Delete Selected'));
  $form['#submit'] = array('trackfield_graph_sizes_submit');
  $form['#validate'] = array('trackfield_graph_sizes_validate');
  
  return $form;
}

function trackfield_graph_theme() {
    return array(
      'trackfield_graph_sizes_form' => array(
        'render element' => 'element',
      ),
      'trackfield_graph_cols_form' => array(
        'render element' => 'element',
      ),
    );
}

function theme_trackfield_graph_sizes_form($element) {
  $header = array(t('Del'), t('Label'), t('Renderer'), t('Width'), t('Height'), t('Axis'), t('Legend'), t('Line'), t('Margins'), t('Font'), t('Size'), t('Resample')); 
  $rows = array();
  $element = $element['element'];

  foreach (element_children($element) as $key) {
    $row = array();	
    $row[] = drupal_render($element[$key]['del']);
    $row[] = drupal_render($element[$key]['label']);
    $row[] = drupal_render($element[$key]['renderer']);
    $row[] = drupal_render($element[$key]['width']);
    $row[] = drupal_render($element[$key]['height']);
    $row[] = drupal_render($element[$key]['axis']);
    $row[] = drupal_render($element[$key]['legend']);
    $row[] = drupal_render($element[$key]['weight']);
    $row[] = drupal_render($element[$key]['margins']);
    $row[] = drupal_render($element[$key]['axis_font']);
    $row[] = drupal_render($element[$key]['axis_font_size']);
    $row[] = drupal_render($element[$key]['resample']);
    $rows[] = $row;
  }
  
  $output = '';
  $output .= theme('table', array('header' => $header,'rows' => $rows));

  return $output;
}

function theme_trackfield_graph_cols_form($element) {
  $header = array(t('Del'), t('Label'), t('Line'), t('Fill'));
  $rows = array();
  $element = $element['element'];
  
  foreach (element_children($element) as $key) {
    $row = array();
    $row[] = drupal_render($element[$key]['del']);
    $row[] = drupal_render($element[$key]['label']);
    $row[] = drupal_render($element[$key]['col']);
    $row[] = drupal_render($element[$key]['fill_col']);
    $rows[] = $row;
  }
  
  $output = '';
  $output .= theme('table', array('header' => $header,'rows' => $rows));
  //$output .= drupal_render($form);

  return $output;
}

function trackfield_graph_sizes_validate($form, &$form_state) {
  /* Don't bother if just deleting what is marked */
  if ($form_state['values']['op'] == t('Delete Selected')) return;

  foreach ($form_state['values']['sizes'] as $key => $config) {
    /* Only check if not empty */
    if (!empty($config['label'])) {
      /* width/height/weight must be > 0 */
      if ($config['width'] < 1) {
        form_set_error("sizes][$key][width", t('Width must be a positive integer.'));
      }
      if ($config['height'] < 1) {
        form_set_error("sizes][$key][height", t('Height must be a positive integer.'));
      }
      if ($config['renderer'] == 'jpgraph') {
        if ($config['weight'] < 1) {
          form_set_error("sizes][$key][weight", t('Line must be a positive integer.'));
        }
        /* There must be 4 margins and must not be negative */
        $margin_parts = explode(',', $config['margins']);
        if (count($margin_parts) != 4) {
          form_set_error("sizes][$key][margins", t('Margin must be specified as "left, right, top, bottom".'));
        } else if (min($margin_parts) < 0) {
          form_set_error("sizes][$key][margins", t('No margins may be negative.'));
        }
        /* Resample doesn't work with fixed fonts */
        if (_trackfield_is_fixed_jpgraph_font($config['axis_font']) &&
            $config['resample'] != 1) {
          form_set_error("sizes][$key][resample", t('Resample does not work with fixed fonts.'));
        }
        if (!_trackfield_is_fixed_jpgraph_font($config['axis_font']) && $config['axis_font_size'] < 1) {
          form_set_error("sizes][$key][axis_font_size", t('Font size must be given and a positive integer where font is not fixed.'));
        }
        if ($config['resample'] < 0) {
          form_set_error("sizes][$key][resample", t('Resample cannot be negative.'));
        }
      }
    }
  }

  if ($form_state['values']['misc']['multiple_fill_threshold'] < 0) {
    form_set_error("misc][multiple_fill_threshold", t('Fill threshold cannot be negative.'));
  }
  if (!is_numeric($form_state['values']['misc']['multiple_fill_threshold'])) {
    form_set_error("misc][multiple_fill_threshold", t('Fill threshold must be numeric.'));
  }
}

function trackfield_graph_sizes_submit($form, &$form_state) {
  if ($form_state['values']['op'] == t('Delete Selected')) {
    /* Load the settings and remove the ones checked for delete */
    $deleted = 0;
    $trackfield_format_sizes = variable_get('trackfield_graph_format_sizes', array());
    foreach ($form_state['values']['sizes'] as $config) {
      if ($config['del']) {
        $key = $config['label'];
        if (array_key_exists($key, $trackfield_format_sizes)) {
          unset($trackfield_format_sizes[$key]);
          $deleted++;
        }
      }
    }
    $trackfield_format_cols = variable_get('trackfield_graph_format_cols', array());
    foreach ($form_state['values']['cols'] as $config) {
      if ($config['del']) {
        $key = $config['label'];
        if (array_key_exists($key, $trackfield_format_cols)) {
          unset($trackfield_format_cols[$key]);
          $deleted++;
        }
      }
    }
    if ($deleted) {
      variable_set('trackfield_graph_format_sizes', $trackfield_format_sizes);
      variable_set('trackfield_graph_format_cols', $trackfield_format_cols);
      drupal_set_message(t('@deleted configuration value@s deleted.', array('@deleted' => $deleted, '@s' => $deleted > 1 ? 's' : '')));
    } else {
      drupal_set_message(t('No valid options to delete.'));
    }

  } else {
    /* Simply build array based on form_values and save it */
    $trackfield_format_sizes = array();
    foreach ($form_state['values']['sizes'] as $lp => $config) {
      if (!empty($config['label'])) {
        $key = $config['label'];
        /* Remove items we don't need to save */
        unset($config['del']);
        unset($config['label']);
        /* And change margins to array */
        $config['margins'] = explode(',', $config['margins']);
        /* Record when settings changed for caching */
        $config['timestamp'] = time();
        $trackfield_format_sizes[$key] = $config;
      }
    }
    variable_set('trackfield_graph_format_sizes', $trackfield_format_sizes);

    $trackfield_format_cols = array();
    foreach ($form_state['values']['cols'] as $lp => $config) {
      if (!empty($config['label'])) {
        $key = $config['label'];
        /* Remove items we don't need to save */
        unset($config['del']);
        unset($config['label']);
        /* And change col/fill_col to array */
        $config['col'] = explode(',', $config['col']);
        $config['fill_col'] = explode(',', $config['fill_col']);
        /* Record when settings changed for caching */
        $config['timestamp'] = time();
        $trackfield_format_cols[$key] = $config;
      }
    }
    variable_set('trackfield_graph_format_cols', $trackfield_format_cols);

    foreach ($form_state['values']['misc'] as $key => $value) {
      variable_set('trackfield_graph_' . $key, $value);
    }

    drupal_set_message(t('The configuration options have been saved.'));
  }
  
  /* TODO: Check view arguments are still valid */
}

