<?php
/**
 * Implements hook_field_schema().
 *
 * This defines the actual database schema of the field, using the format
 * used by the Schema API.
 *
 *
 * @see hook_field_schema()
 * @link schemaapi Schema API @endlink
 */
 
function trackfield_wkt_field_schema($field) {
  $columns = array(
  	 // Value is the raw input
    'value' => array('type' => 'text', 'size' => 'big', 'sortable' => FALSE),
  );
  return array(
    'columns' => $columns,
  );
}