<?php
/**
 * @file
 * Parses GPX XML formats for track data.
 */

/*
 * Types of input we understand.
 */
DEFINE('DATASET_GPX', 'gpx');

/*
 * Implements hook_trackfield_valuetypes().
 */
function trackfield_gpx_trackfield_valuetypes() {
  return array(
    DATASET_GPX => t('GPX'),
  );
}

function _trackfield_gpx_setcsv(&$item) {
  $new_value = FALSE;
  $doc = new DomDocument;
  if ($doc->loadXML($item['value'])) {
    $course = $doc->getElementsByTagName('trk');
    if ($course->length) {
      $pointname = 'trkpt';
      $point_list = $course->item(0)->getElementsByTagName($pointname);
      $point = $point_list->item(0);
      while ($point) {
        $lat = trim($point->getAttributeNode('lat')->value);
        $lon = trim($point->getAttributeNode('lon')->value);
        $alt = trim($point->getElementsByTagName('ele')->item(0)->nodeValue);
        // Extract time from GPX.
        $tim = trim($point->getElementsByTagName('time')->item(0)->nodeValue);
        // Convert time into number of seconds since start.
        if ($tim) {
          $tim = strtotime($tim);
          if (!isset($csv)) { $tim_base = $tim; }
          $tim = $tim - $tim_base;
        }
        if (isset($csv)) { $csv .= ' '; }
        $csv .= "$lon,$lat,$alt,$tim";
        
        // Move to next point of interest in the list.
        do {
          $point = $point->nextSibling;
        } while ($point && $point->nodeName != $pointname);
      }
      $new_value = $csv;
      $item['valuetype'] = DATASET_LONLATALT;
    }
  }
  $item['value'] = $new_value;
}

/*
 * Implements hook_trackfield_validate().
 */
function trackfield_gpx_trackfield_validate($item, $node, $delta, $langcode) {
  $valuetype = $item['valuetype'];
  if (!array_key_exists($valuetype, trackfield_gpx_trackfield_valuetypes())) { return; }

  _trackfield_gpx_setcsv($item);
  if (!$item['value']) {
    return array('trackfield_gpx_invalid_data' => t('Invalid gpx or no paths found in gpx.'));
  }
  return trackfield_csv_trackfield_validate($item, $node, $delta, $langcode);
}

/*
 * Implements hook_trackfield_submit().
 */
function trackfield_gpx_trackfield_submit($item, $node, $delta, $langcode) {
  $valuetype = $item['valuetype'];
  if (!array_key_exists($valuetype, trackfield_gpx_trackfield_valuetypes())) { return; }

  _trackfield_gpx_setcsv($item);
  return trackfield_csv_trackfield_submit($item, $node, $delta, $langcode);
}
